config/routes.rb
Rails.application.routes.draw do
  get 'months/index'
  get 'posts/index'
  devise_for :users
  get 'welcomes/index'
  root to: "welcomes#index"
  resources :spendings, only:[:new, :create]
  resources :incomes, only:[:new, :create]
  resources :posts, only:[:index]
  resources :months, only:[:index] do
    collection do
      get 'last_month'
    end
  end
  resources :years, only:[:index] do
    collection do
      get 'last_year'
    end
  end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def index
    @spending_months = Spending.where(created_at: Date.today.all_month)
    @spending_categories_month = @spending_months.spending_category_for_graph
    @spending_months_food = @spending_months.where(spending_category_id: 1)
    @spending_months_daily = @spending_months.where(spending_category_id: 2)
    @spending_months_house = @spending_months.where(spending_category_id: 3)
    @spending_months_infrastructure = @spending_months.where(spending_category_id: 4)
    @spending_months_communication = @spending_months.where(spending_category_id: 5)
    @spending_months_transport = @spending_months.where(spending_category_id: 6)
    @spending_months_entertainment = @spending_months.where(spending_category_id: 7)
    @spending_months_beauty = @spending_months.where(spending_category_id: 8)
    @spending_months_self_investment = @spending_months.where(spending_category_id: 9)
    @spending_months_health = @spending_months.where(spending_category_id: 10)
    @spending_months_other = @spending_months.where(spending_category_id: 11)
    @income_months = Income.where(created_at: Date.today.all_month)
    @income_months_salary = @income_months.where(income_category_id: 1)
    @income_months_bonus = @income_months.where(income_category_id: 2)
    @income_months_supplementary_income = @income_months.where(income_category_id: 3)
    @income_months_extraordinary_income = @income_months.where(income_category_id: 4)
  end

  def last_month
    @spending_last_month = Spending.where(created_at: Date.today.last_month.beginning_of_month..Date.today.last_month.end_of_month)
    @spending_last_month_month = @spending_last_month.spending_category_for_graph
    @spending_last_month_food = @spending_last_month.where(spending_category_id: 1)
    @spending_last_month_daily = @spending_last_month.where(spending_category_id: 2)
    @spending_last_month_house = @spending_last_month.where(spending_category_id: 3)
    @spending_last_month_infrastructure = @spending_last_month.where(spending_category_id: 4)
    @spending_last_month_communication = @spending_last_month.where(spending_category_id: 5)
    @spending_last_month_transport = @spending_last_month.where(spending_category_id: 6)
    @spending_last_month_entertainment = @spending_last_month.where(spending_category_id: 7)
    @spending_last_month_beauty = @spending_last_month.where(spending_category_id: 8)
    @spending_last_month_self_investment = @spending_last_month.where(spending_category_id: 9)
    @spending_last_month_health = @spending_last_month.where(spending_category_id: 10)
    @spending_last_month_other = @spending_last_month.where(spending_category_id: 11)
    @income_last_months = Income.where(created_at: Date.today.last_month.beginning_of_month..Date.today.last_month.end_of_month)
    @income_last_months_salary = @income_last_months.where(income_category_id: 1)
    @income_last_months_bonus = @income_last_months.where(income_category_id: 2)
    @income_last_months_supplementary_income = @income_last_months.where(income_category_id: 3)
    @income_last_months_extraordinary_income = @income_last_months.where(income_category_id: 4)
  end
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/views/months/index.html.erb
<%= render "share/header" %>

<div class="post-main">
  <div class="page-change-class">
    <%= link_to "登録一覧", posts_path, class:"page-change-btn"%>
    <%= link_to "月間分析", months_path, class:"page-change-btn"%>
    <%= link_to "年間分析", years_path, class:"page-change-btn"%>
  </div>
  <div class="month-contents-all">
    <div class="month-contents-all-title">
      <%= "#{Date.today.month}月の月間分析"%>
    </div>
    <div class="last-month-btn">
      <%= link_to "<<#{Date.today.month-1}月の月間分析", last_month_months_path %>
    </div>
    <div class="month-line_chart">
      <div class="month-line-graph-title">
      支出遷移
      </div>
      <div class="month-line_chart-content">
        <% if @spending_months.present?%>
          <%= column_chart @spending_months.group_by_day(:created_at).sum(:price), width: "800px", height: "200px", discrete: true, ytitle: "支出金額", thousands: "," %>
        <% else %>
           <%= "#{Date.today.month}月の支出登録はありません" %>
        <% end %>
      </div>
    </div>

    <div class="month-contents-under">
      <div class="month-line_chart">
        <div class="month-graph-title">
        支出内訳
        </div>
        <div class="month-pie_chart-content">
          <% if @spending_months.present?%>
            <%= pie_chart @spending_categories_month %>
          <% else %>
            <%= "#{Date.today.month}月の支出登録はありません" %>
          <% end %>
        </div>
      </div>

      <div class="month-analysis">
        <div class="month-graph-title">
        支出分析
        </div>
        <div class="month-analysis-contents">
           <% if @spending_months.present? %>
            <ul class="month-analysis-contents-list">
              <li class="month-analysis-title"><%= "#{Date.today.month}月の支出合計:#{@spending_months.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "食費:#{@spending_months_food.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "日用品:#{@spending_months_daily.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "家賃:#{@spending_months_house.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "電気・ガス・水道:#{@spending_months_infrastructure.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "通信費:#{@spending_months_communication.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "交通費:#{@spending_months_transport.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "交際費:#{@spending_months_entertainment.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "美容・ファッション:#{@spending_months_beauty.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "自己投資:#{@spending_months_self_investment.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "病院:#{@spending_months_health.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "その他:#{@spending_months_other.sum(:price)}円" %></li>
            </ul>
          <% else %>
            <%= "#{Date.today.month}月の支出登録はありません" %>
          <% end %>
        </div>
      </div>

      <div class="month-analysis">
        <div class="month-graph-title">
        収入分析
        </div>
        <div class="month-analysis-contents">
          <% if @income_months.present? %>
            <ul class="month-analysis-contents-list">
              <li class="month-analysis-title"><%= "#{Date.today.month}月の収入合計:#{@income_months.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "給与:#{@income_months_salary.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "賞与:#{@income_months_bonus.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "家賃:#{@income_months_supplementary_income.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "電気・ガス・水道:#{@income_months_extraordinary_income.sum(:price)}円" %></li>
            </ul>
          <% else %>
            <%= "#{Date.today.month}月の収入登録はありません" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

<%= render "share/footer" %>

app/views/months/last_month.html.erb
<%= render "share/header" %>

<div class="post-main">
  <div class="page-change-class">
    <%= link_to "登録一覧", posts_path, class:"page-change-btn"%>
    <%= link_to "月間分析", months_path, class:"page-change-btn"%>
    <%= link_to "年間分析", years_path, class:"page-change-btn"%>
  </div>
  <div class="month-contents-all">
    <div class="month-contents-all-title">
      <%= "#{Date.today.month-1}月の月間分析"%>
    </div>
    <div class="this-month-btn">
      <%= link_to "#{Date.today.month}月の月間分析>>", months_path %>
    </div>
    <div class="month-line_chart">
      <div class="month-line-graph-title">
      支出遷移
      </div>
      <div class="month-line_chart-content">
        <% if @spending_last_month.present?%>
          <%= column_chart @spending_last_month.group_by_day(:created_at).sum(:price), width: "800px", height: "200px", discrete: true, ytitle: "支出金額", thousands: "," %>
        <% else %>
           <%= "#{Date.today.month - 1}月の支出登録はありません" %>
        <% end %>
      </div>
    </div>

    <div class="month-contents-under">
      <div class="month-line_chart">
        <div class="month-graph-title">
        支出内訳
        </div>
        <div class="month-pie_chart-content">
          <% if @spending_last_month.present?%>
            <%= pie_chart @spending_last_month_month %>
          <% else %>
            <%= "#{Date.today.month - 1}月の支出登録はありません" %>
          <% end %>
        </div>
      </div>

      <div class="month-analysis">
        <div class="month-graph-title">
        支出分析
        </div>
        <div class="month-analysis-contents">
          <% if @spending_last_month.present?%>
            <ul class="month-analysis-contents-list">
              <li class="month-analysis-title"><%= "#{Date.today.month-1}月の支出合計:#{@spending_last_month.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "食費:#{@spending_last_month_food.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "日用品:#{@spending_last_month_daily.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "家賃:#{@spending_last_month_house.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "電気・ガス・水道:#{@spending_last_month_infrastructure.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "通信費:#{@spending_last_month_communication.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "交通費:#{@spending_last_month_transport.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "交際費:#{@spending_last_month_entertainment.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "美容・ファッション:#{@spending_last_month_beauty.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "自己投資:#{@spending_last_month_self_investment.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "病院:#{@spending_last_month_health.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "その他:#{@spending_last_month_other.sum(:price)}円" %></li>
            </ul>
        <% else %>
            <%= "#{Date.today.month - 1}月の支出登録はありません" %>
        <% end %>
        </div>
      </div>

      <div class="month-analysis">
        <div class="month-graph-title">
        収入分析
        </div>
        <div class="month-analysis-contents">
          <% if @income_last_months.present?%>
            <ul class="month-analysis-contents-list">
              <li class="month-analysis-title"><%= "#{Date.today.month -1 }月の収入合計:#{@income_last_months.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "給与:#{@income_last_months_salary.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "賞与:#{@income_last_months_bonus.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "家賃:#{@income_last_months_supplementary_income.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "電気・ガス・水道:#{@income_last_months_extraordinary_income.sum(:price)}円" %></li>
            </ul>
          <% else %>
            <%= "#{Date.today.month - 1}月の収入登録はありません" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

<%= render "share/footer" %>