config/routes.rb
Rails.application.routes.draw do
  get 'months/index'
  get 'posts/index'
  devise_for :users
  get 'welcomes/index'
  root to: "welcomes#index"
  resources :spendings, only:[:new, :create]
  resources :incomes, only:[:new, :create]
  resources :posts, only:[:index]
  resources :months, only:[:index] do
    collection do
      get 'last_month'
    end
  end
  resources :years, only:[:index] do
    collection do
      get 'last_year'
    end
  end
end

app/views/share/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message">
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/share/_footer.html.erb
<footer>©かんたん家計簿</footer>

app/views/share/_header.html.erb
<header>
  <div class="header-main">
    <div class="header-left">
      <%= link_to "かんたん家計簿", root_path , class:"header-title"%>
    </div>
    <div class="header-right">
      <% if user_signed_in? %>
        <%= link_to "支出登録", new_spending_path, class:"header-right-btn" %>
        <%= link_to "収入登録", new_income_path, class:"header-right-btn" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"header-right-btn" %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path, class:"header-right-btn" %>
        <%= link_to "新規登録", new_user_registration_path, class:"header-right-btn" %>
      <% end %>
    <div>
  </div>
</header>