config/routes.rb
Rails.application.routes.draw do
  get 'months/index'
  get 'posts/index'
  devise_for :users
  get 'welcomes/index'
  root to: "welcomes#index"
  resources :spendings, only:[:new, :create]
  resources :incomes, only:[:new, :create]
  resources :posts, only:[:index]
  resources :months, only:[:index] do
    collection do
      get 'last_month'
    end
  end
  resources :years, only:[:index] do
    collection do
      get 'last_year'
    end
  end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  def index
    @spending_years = Spending.where(created_at: Date.today.all_year)
    @spending_categories_year = @spending_years.spending_category_for_graph
    @spending_years_food = @spending_years.where(spending_category_id: 1)
    @spending_years_daily = @spending_years.where(spending_category_id: 2)
    @spending_years_house = @spending_years.where(spending_category_id: 3)
    @spending_years_infrastructure = @spending_years.where(spending_category_id: 4)
    @spending_years_communication = @spending_years.where(spending_category_id: 5)
    @spending_years_transport = @spending_years.where(spending_category_id: 6)
    @spending_years_entertainment = @spending_years.where(spending_category_id: 7)
    @spending_years_beauty = @spending_years.where(spending_category_id: 8)
    @spending_years_self_investment = @spending_years.where(spending_category_id: 9)
    @spending_years_health = @spending_years.where(spending_category_id: 10)
    @spending_years_other = @spending_years.where(spending_category_id: 11)
    @income_years = Income.where(created_at: Date.today.all_year)
    @income_years_salary = @income_years.where(income_category_id: 1)
    @income_years_bonus = @income_years.where(income_category_id: 2)
    @income_years_supplementary_income = @income_years.where(income_category_id: 3)
    @income_years_extraordinary_income = @income_years.where(income_category_id: 4)
  end

  def last_year
    @spending_last_year = Spending.where(created_at: Date.today.last_year.beginning_of_month..Date.today.last_year.end_of_month)
    @spending_last_year_year = @spending_last_year.spending_category_for_graph
    @spending_last_year_food = @spending_last_year.where(spending_category_id: 1)
    @spending_last_year_daily = @spending_last_year.where(spending_category_id: 2)
    @spending_last_year_house = @spending_last_year.where(spending_category_id: 3)
    @spending_last_year_infrastructure = @spending_last_year.where(spending_category_id: 4)
    @spending_last_year_communication = @spending_last_year.where(spending_category_id: 5)
    @spending_last_year_transport = @spending_last_year.where(spending_category_id: 6)
    @spending_last_year_entertainment = @spending_last_year.where(spending_category_id: 7)
    @spending_last_year_beauty = @spending_last_year.where(spending_category_id: 8)
    @spending_last_year_self_investment = @spending_last_year.where(spending_category_id: 9)
    @spending_last_year_health = @spending_last_year.where(spending_category_id: 10)
    @spending_last_year_other = @spending_last_year.where(spending_category_id: 11)
    @income_last_years = Income.where(created_at: Date.today.last_year.beginning_of_month..Date.today.last_year.end_of_month)
    @income_last_years_salary = @income_last_years.where(income_category_id: 1)
    @income_last_years_bonus = @income_last_years.where(income_category_id: 2)
    @income_last_years_supplementary_income = @income_last_years.where(income_category_id: 3)
    @income_last_years_extraordinary_income = @income_last_years.where(income_category_id: 4)
  end
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/index.html.erb
<%= render "share/header" %>

<div class="post-main">
  <div class="page-change-class">
    <%= link_to "登録一覧", posts_path, class:"page-change-btn"%>
    <%= link_to "月間分析", months_path, class:"page-change-btn"%>
    <%= link_to "年間分析", years_path, class:"page-change-btn"%>
  </div>
  <div class="month-contents-all">
    <div class="month-contents-all-title">
      <%= "#{Date.today.year}年の年間分析"%>
    </div>
    <div class="last-month-btn">
      <%= link_to "<<#{Date.today.year-1}年の年間分析", last_year_years_path %>
    </div>
    <div class="month-line_chart">
      <div class="month-line-graph-title">
      支出遷移
      </div>
      <div class="month-line_chart-content">
        <% if @spending_years.present?%>
          <%= column_chart @spending_years.group_by_month(:created_at, format: "%-m月").sum(:price), width: "800px", height: "200px", ytitle: "支出金額", thousands: "," %>
        <% else %>
           <%= "#{Date.today.year}年の支出登録はありません"%>
        <% end %>
      </div>
    </div>

    <div class="month-contents-under">
      <div class="month-line_chart">
        <div class="month-graph-title">
        支出内訳
        </div>
        <div class="month-pie_chart-content">
          <% if @spending_years.present?%>
            <%= pie_chart @spending_categories_year %>
          <% else %>
            <%= "#{Date.today.year}年の支出登録はありません"%>
          <% end %>
        </div>
      </div>

      <div class="month-analysis">
        <div class="month-graph-title">
        支出分析
        </div>
        <div class="month-analysis-contents">
          <% if @spending_years.present? %>
            <ul class="month-analysis-contents-list">
              <li class="month-analysis-title"><%= "#{Date.today.year}年の支出合計:#{@spending_years.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "食費:#{@spending_years_food.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "日用品:#{@spending_years_daily.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "家賃:#{@spending_years_house.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "電気・ガス・水道:#{@spending_years_infrastructure.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "通信費:#{@spending_years_communication.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "交通費:#{@spending_years_transport.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "交際費:#{@spending_years_entertainment.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "美容・ファッション:#{@spending_years_beauty.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "自己投資:#{@spending_years_self_investment.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "病院:#{@spending_years_health.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "その他:#{@spending_years_other.sum(:price)}円" %></li>
            </ul>
          <% else %>
            <%= "#{Date.today.year}年の支出登録はありません"%>
          <% end %>
        </div>
      </div>

      <div class="month-analysis">
        <div class="month-graph-title">
        収入分析
        </div>
        <div class="month-analysis-contents">
          <% if @income_years.present? %>
            <ul class="month-analysis-contents-list">
              <li class="month-analysis-title"><%= "#{Date.today.year}年の収入合計:#{@income_years.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "給与:#{@income_years_salary.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "賞与:#{@income_years_bonus.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "家賃:#{@income_years_supplementary_income.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "電気・ガス・水道:#{@income_years_extraordinary_income.sum(:price)}円" %></li>
            </ul>
          <% else %>
            <%= "#{Date.today.year}年の収入登録はありません" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

<%= render "share/footer" %>

app/views/years/last_year.html.erb
<%= render "share/header" %>

<div class="post-main">
  <div class="page-change-class">
    <%= link_to "登録一覧", posts_path, class:"page-change-btn"%>
    <%= link_to "月間分析", months_path, class:"page-change-btn"%>
    <%= link_to "年間分析", years_path, class:"page-change-btn"%>
  </div>
  <div class="month-contents-all">
    <div class="month-contents-all-title">
      <%= "#{Date.today.year-1}年の年間分析"%>
    </div>
    <div class="this-month-btn">
      <%= link_to "#{Date.today.year}年の年間分析>>", years_path %>
    </div>
    <div class="month-line_chart">
      <div class="month-line-graph-title">
      支出遷移
      </div>
      <div class="month-line_chart-content">
        <% if @spending_last_year.present?%>
          <%= column_chart @spending_last_year.group_by_month(:created_at, format: "%-m月").sum(:price), width: "800px", height: "200px", discrete: true, ytitle: "支出金額", thousands: "," %>
        <% else %>
           <%= "#{Date.today.year-1}年の支出登録はありません"%>
        <% end %>
      </div>
    </div>

    <div class="month-contents-under">
      <div class="month-line_chart">
        <div class="month-graph-title">
        支出内訳
        </div>
        <div class="month-pie_chart-content">
          <% if @spending_last_year.present?%>
            <%= pie_chart @spending_last_year_year %>
          <% else %>
            <%= "#{Date.today.year-1}年の支出登録はありません"%>
          <% end %>
        </div>
      </div>

      <div class="month-analysis">
        <div class="month-graph-title">
        支出分析
        </div>
        <div class="month-analysis-contents">
          <% if @spending_last_year.present? %>
            <ul class="month-analysis-contents-list">
              <li class="month-analysis-title"><%= "#{Date.today.year-1}年の支出合計:#{@spending_last_year.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "食費:#{@spending_last_year_food.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "日用品:#{@spending_last_year_daily.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "家賃:#{@spending_last_year_house.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "電気・ガス・水道:#{@spending_last_year_infrastructure.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "通信費:#{@spending_last_year_communication.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "交通費:#{@spending_last_year_transport.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "交際費:#{@spending_last_year_entertainment.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "美容・ファッション:#{@spending_last_year_beauty.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "自己投資:#{@spending_last_year_self_investment.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "病院:#{@spending_last_year_health.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "その他:#{@spending_last_year_other.sum(:price)}円" %></li>
            </ul>
          <% else %>
            <%= "#{Date.today.year-1}年の支出登録はありません"%>
          <% end %>
        </div>
      </div>

      <div class="month-analysis">
        <div class="month-graph-title">
        収入分析
        </div>
        <div class="month-analysis-contents">
          <% if @income_last_years.present? %>
            <ul class="month-analysis-contents-list">
              <li class="month-analysis-title"><%= "#{Date.today.year - 1 }年の収入合計:#{@income_last_years.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "給与:#{@income_last_years_salary.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "賞与:#{@income_last_years_bonus.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "家賃:#{@income_last_years_supplementary_income.sum(:price)}円" %></li>
              <li class="month-analysis-content"><%= "電気・ガス・水道:#{@income_last_years_extraordinary_income.sum(:price)}円" %></li>
            </ul>
          <% else %>
            <%= "#{Date.today.year-1}年の収入登録はありません" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

<%= render "share/footer" %>